#-------------------- Params --------------------
samplesheet: "/farmshare/home/classes/bios/270/data/samplesheet.csv"
index: '/farmshare/home/classes/bios/270/data/indexes/ecoli_transcripts_index'
outdir: '/farmshare/user_data/odunkley/bios270/rnaseq_nf/processed_data/SRP628437_nf'
run_deseq: true
transcriptome: '/farmshare/home/classes/bios/270/data/ecoli_ref/GCF_000401755.1_Escherichia_coli_ATCC_25922_cds_from_genomic.fna'
